sudo: required
# Enable C++ support
 language: cpp
 # Compiler selection
 compiler:
   - clang
    - gcc
     # Build steps
     script:
       - mkdir build
         - cd build
           - cmake .. && make

deploy:
  provider: releases
  api_key: "81264abad3aa08034b327bff23002217c969bf0d"
  file: "README.MD"
  skip_cleanup: true
  on:
    tags: true

