sudo: required
before_install:
    - script ./travis/install-linux.sh
script:
    # скрипт сборки и тестирования проекта:
    - mkdir build
    - cd build
    - cmake ../
language: cpp
compiler:
  - gcc
script: pwd
- cd ..
script: pwd
build:
    - script: ./travis/build.sh
os:
- linux
branches:
  only:
  - master
