# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-6
    - g++-6

deploy:
  provider: releases
  api_key: "81264abad3aa08034b327bff23002217c969bf0d"
  file: "README.MD"
  skip_cleanup: true
  on:
    tags: true

