sudo: required
install:
    - script ./travis/install-linux.sh
    - cd ..
    - pwd
language: cpp

compiler:
  - gcc

build:
    - script ./build.sh
os:
- linux

branches:
  only:
  - master

deploy:
  provider: releases
  api_key: "81264abad3aa08034b327bff23002217c969bf0d"
  file: "README.MD"
  skip_cleanup: true
  on:
    tags: true

