sudo: required
before_install:
    - script ./travis/install-linux.sh
language: cpp
compiler:
  - gcc
script: pwd
- cd ..
script: pwd
build:
    - script ./build.sh
os:
- linux

branches:
  only:
  - master

deploy:
  provider: releases
  api_key: "81264abad3aa08034b327bff23002217c969bf0d"
  file: "README.MD"
  skip_cleanup: true
  on:
    tags: true

