install:
    - script ./travis/install-linux.sh
    - source ./travis/install-linux.sh: 
build:
    - script: ./travis/build.sh
language: cpp
  addons:
    apt:
      update: true
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux
branches:
  only:
  - master
