sudo: required
before_install:
    - script ./travis/install-linux.sh
    - source ./travis/install-linux.sh: 
language: cpp
compiler:
  - gcc
script: pwd
- cd ..
script: pwd
build:
    - script: ./travis/build.sh
os:
- linux
branches:
  only:
  - master
